declare module 'three';
declare module 'three/examples/jsm/loaders/GLTFLoader.js';
declare module 'three/examples/jsm/loaders/OBJLoader.js';
declare module 'three/examples/jsm/loaders/STLLoader.js';
declare module 'three/examples/jsm/loaders/FBXLoader.js';
declare module 'three/examples/jsm/controls/OrbitControls.js';
declare module 'three/examples/jsm/loaders/GLTFLoader.js';
declare module 'three/examples/jsm/loaders/DRACOLoader.js';
declare module 'three/examples/jsm/controls/OrbitControls.js';